# Generated by Django 5.2 on 2024-11-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentsrest', '0002_appointment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
